// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TH.TownHub.Infrastructure.Database;

#nullable disable

namespace TH.WebAPI.Migrations.TownHubDb
{
    [DbContext(typeof(TownHubDbContext))]
    [Migration("20260410065007_TownHubV1")]
    partial class TownHubV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaM2")
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Building", "Floor", "UnitNumber")
                        .IsUnique();

                    b.ToTable("apartments", "auth");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActorAuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewData")
                        .HasColumnType("text");

                    b.Property<string>("OldData")
                        .HasColumnType("text");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,0)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("BillingMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("ApartmentId", "FeeTypeId", "BillingMonth")
                        .IsUnique();

                    b.ToTable("fees", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerM2")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(14,0)");

                    b.HasKey("Id");

                    b.ToTable("fee_types", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7482),
                            Description = "Phí quản lý hàng tháng",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí quản lý",
                            UnitPrice = 800000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7490),
                            Description = "Phí dịch vụ tiện ích",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí dịch vụ",
                            UnitPrice = 500000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7493),
                            Description = "Phí giữ xe hàng tháng",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí gửi xe",
                            UnitPrice = 300000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7494),
                            Description = "Phí vệ sinh chung cư",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí vệ sinh",
                            UnitPrice = 50000m
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FileStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UploadedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("files", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("incidents", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.IncidentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<int>("AuthorAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_comments", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("notifications", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("notification_logs", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variables")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("notification_templates", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .HasColumnType("text");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MoveInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("IdCard")
                        .IsUnique()
                        .HasFilter("\"IdCard\" IS NOT NULL");

                    b.ToTable("residents", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_configs", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "string",
                            Description = "Tên dự án hiển thị",
                            IsPublic = true,
                            Key = "project_name",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7254),
                            Value = "TownHub"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "string",
                            Description = "Mã dự án (bất biến)",
                            IsPublic = false,
                            Key = "project_code",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7259),
                            Value = "LUX_RES_01"
                        },
                        new
                        {
                            Id = 3,
                            DataType = "string",
                            Description = "Email hỗ trợ BQL",
                            IsPublic = true,
                            Key = "support_email",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7261),
                            Value = "support@TownHub.vn"
                        },
                        new
                        {
                            Id = 4,
                            DataType = "string",
                            Description = "Hotline liên hệ",
                            IsPublic = true,
                            Key = "hotline",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7263),
                            Value = "1900 1234"
                        },
                        new
                        {
                            Id = 5,
                            DataType = "boolean",
                            Description = "Bật/tắt chế độ bảo trì",
                            IsPublic = false,
                            Key = "maintenance_mode",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7264),
                            Value = "false"
                        },
                        new
                        {
                            Id = 6,
                            DataType = "string",
                            Description = "Nhà cung cấp SMS",
                            IsPublic = false,
                            Key = "sms_gateway",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7266),
                            Value = "ESMS"
                        },
                        new
                        {
                            Id = 7,
                            DataType = "string",
                            Description = "Cổng thanh toán hỗ trợ",
                            IsPublic = false,
                            Key = "payment_gateways",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7267),
                            Value = "VNPay,MoMo"
                        },
                        new
                        {
                            Id = 8,
                            DataType = "integer",
                            Description = "Giới hạn thông báo/ngày",
                            IsPublic = false,
                            Key = "max_notification_daily",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7269),
                            Value = "50"
                        },
                        new
                        {
                            Id = 9,
                            DataType = "string",
                            Description = "Nơi lưu trữ file",
                            IsPublic = false,
                            Key = "storage_provider",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7270),
                            Value = "AWS S3"
                        },
                        new
                        {
                            Id = 10,
                            DataType = "integer",
                            Description = "Timeout phiên đăng nhập (phút)",
                            IsPublic = false,
                            Key = "session_timeout_min",
                            UpdatedAt = new DateTime(2026, 4, 10, 6, 50, 7, 433, DateTimeKind.Utc).AddTicks(7272),
                            Value = "30"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Fee", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Fees")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.TownHub.Domain.Entities.FeeType", "FeeType")
                        .WithMany("Fees")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Incidents")
                        .HasForeignKey("ApartmentId");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.IncidentComment", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.NotificationTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Notification", "Notification")
                        .WithMany("Logs")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.TownHub.Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId");

                    b.Navigation("Notification");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Resident", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Incidents");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FeeType", b =>
                {
                    b.Navigation("Fees");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
