// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TH.TownHub.Infrastructure.Database;

#nullable disable

namespace TH.WebAPI.Migrations.TownHubDb
{
    [DbContext(typeof(TownHubDbContext))]
    [Migration("20260716161430_AddFloorsAndApartmentFloorId")]
    partial class AddFloorsAndApartmentFloorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TH.Base.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("managementCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("totalFloors")
                        .HasColumnType("integer");

                    b.Property<int>("totalUnits")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("buildings", "base");
                });

            modelBuilder.Entity("TH.Base.Domain.Entities.Floor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("buildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("floorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("floorNumber")
                        .HasColumnType("integer");

                    b.Property<string>("floorType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("id");

                    b.HasIndex("buildingId", "floorNumber")
                        .IsUnique();

                    b.ToTable("floors", "base");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.AccessEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HandledByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.HasIndex("PersonType", "DetectedAt");

                    b.ToTable("access_events", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaM2")
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Building", "Floor", "UnitNumber")
                        .IsUnique();

                    b.ToTable("apartments", "auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaM2 = 70.5m,
                            Building = "Tòa A",
                            Code = "A0101",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "occupied",
                            Type = "2PN",
                            UnitNumber = "01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AreaM2 = 95.0m,
                            Building = "Tòa A",
                            Code = "A0102",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "occupied",
                            Type = "3PN",
                            UnitNumber = "02",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AreaM2 = 45.0m,
                            Building = "Tòa A",
                            Code = "A0201",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            Status = "vacant",
                            Type = "1PN",
                            UnitNumber = "01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AreaM2 = 35.0m,
                            Building = "Tòa A",
                            Code = "A0202",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            Status = "maintenance",
                            Type = "Studio",
                            UnitNumber = "02",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AreaM2 = 110.0m,
                            Building = "Tòa B",
                            Code = "B0101",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "occupied",
                            Type = "3PN",
                            UnitNumber = "01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AreaM2 = 68.0m,
                            Building = "Tòa B",
                            Code = "B0102",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "occupied",
                            Type = "2PN",
                            UnitNumber = "02",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AreaM2 = 250.0m,
                            Building = "Villa",
                            Code = "V0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "occupied",
                            Type = "Villa",
                            UnitNumber = "01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AreaM2 = 300.0m,
                            Building = "Villa",
                            Code = "V0002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 1,
                            Status = "vacant",
                            Type = "Villa",
                            UnitNumber = "02",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AreaM2 = 72.0m,
                            Building = "Tòa A",
                            Code = "A0505",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 5,
                            Status = "occupied",
                            Type = "2PN",
                            UnitNumber = "05",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AreaM2 = 180.0m,
                            Building = "Tòa B",
                            Code = "B1201",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 12,
                            Status = "occupied",
                            Type = "Penthouse",
                            UnitNumber = "01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActorAuthUserId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewData")
                        .HasColumnType("text");

                    b.Property<string>("OldData")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "CREATE_NOTIFICATION",
                            ActorAuthUserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpAddress = "192.168.1.10",
                            NewData = "{\"Title\":\"Bảo trì thang máy Tòa A\"}",
                            TargetId = 1,
                            TargetType = "Notification",
                            UserAgent = "Chrome/120.0.0"
                        },
                        new
                        {
                            Id = 2L,
                            Action = "RESOLVE_INCIDENT",
                            ActorAuthUserId = 201,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpAddress = "192.168.1.15",
                            NewData = "{\"Status\":\"resolved\"}",
                            OldData = "{\"Status\":\"open\"}",
                            TargetId = 1,
                            TargetType = "Incident",
                            UserAgent = "TownHubStaffApp/1.0"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "PAY_FEE",
                            ActorAuthUserId = 101,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpAddress = "113.190.23.45",
                            NewData = "{\"Status\":\"paid\"}",
                            OldData = "{\"Status\":\"unpaid\"}",
                            TargetId = 1,
                            TargetType = "Fee",
                            UserAgent = "TownHubResidentApp/1.0"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FaceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EmbeddingRef")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId")
                        .IsUnique();

                    b.ToTable("face_profiles", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,0)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("BillingMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("ApartmentId", "FeeTypeId", "BillingMonth")
                        .IsUnique();

                    b.ToTable("fees", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 800000m,
                            ApartmentId = 1,
                            BillingMonth = "2024-01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeTypeId = 1,
                            Note = "Thanh toán đúng hạn",
                            PaidAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "VNPay",
                            PaymentRef = "VNP123456",
                            Status = "paid",
                            UpdatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300000m,
                            ApartmentId = 1,
                            BillingMonth = "2024-01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeTypeId = 3,
                            PaidAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "VNPay",
                            PaymentRef = "VNP123457",
                            Status = "paid",
                            UpdatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1200000m,
                            ApartmentId = 5,
                            BillingMonth = "2024-01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeTypeId = 1,
                            Status = "unpaid",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 500000m,
                            ApartmentId = 5,
                            BillingMonth = "2024-01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeTypeId = 2,
                            Status = "unpaid",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5000000m,
                            ApartmentId = 7,
                            BillingMonth = "2024-01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeTypeId = 1,
                            PaidAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Bank Transfer",
                            PaymentRef = "VCB999888",
                            Status = "paid",
                            UpdatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerM2")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(14,0)");

                    b.HasKey("Id");

                    b.ToTable("fee_types", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phí quản lý hàng tháng",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí quản lý",
                            UnitPrice = 800000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phí dịch vụ tiện ích",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí dịch vụ",
                            UnitPrice = 500000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phí giữ xe hàng tháng",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí gửi xe",
                            UnitPrice = 300000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phí vệ sinh chung cư",
                            IsActive = true,
                            IsPerM2 = false,
                            Name = "Phí vệ sinh",
                            UnitPrice = 50000m
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FileStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UploadedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("files", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = 1,
                            EntityType = "incident",
                            MimeType = "image/jpeg",
                            OriginalName = "bong_den_hong.jpg",
                            SizeBytes = 1024500L,
                            StorageKey = "incidents/2024/01/bong_den_hong_abc123.jpg",
                            UploadedByAuthUserId = 101,
                            Url = "https://townhub-s3.amazonaws.com/incidents/2024/01/bong_den_hong_abc123.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = 2,
                            EntityType = "incident",
                            MimeType = "image/png",
                            OriginalName = "tran_nha_tham.png",
                            SizeBytes = 3500200L,
                            StorageKey = "incidents/2024/01/tran_nha_tham_xyz789.png",
                            UploadedByAuthUserId = 104,
                            Url = "https://townhub-s3.amazonaws.com/incidents/2024/01/tran_nha_tham_xyz789.png"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = 1,
                            EntityType = "resident",
                            MimeType = "image/jpeg",
                            OriginalName = "avatar_tuan.jpg",
                            SizeBytes = 500000L,
                            StorageKey = "avatars/101/avatar_tuan.jpg",
                            UploadedByAuthUserId = 101,
                            Url = "https://townhub-s3.amazonaws.com/avatars/101/avatar_tuan.jpg"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("incidents", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            AssignedToAuthUserId = 201,
                            Category = "electrical",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bóng đèn trước cửa căn A0101 bị cháy.",
                            Location = "Hành lang Tòa A Tầng 1",
                            Priority = "low",
                            ReportedByAuthUserId = 101,
                            ResolutionNote = "Đã thay bóng mới.",
                            ResolvedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "resolved",
                            Title = "Bóng đèn hành lang tầng 1 hỏng",
                            UpdatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 5,
                            AssignedToAuthUserId = 202,
                            Category = "plumbing",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trần nhà vệ sinh master bị thấm nước từ tầng trên.",
                            Location = "WC Master",
                            Priority = "high",
                            ReportedByAuthUserId = 104,
                            Status = "in_progress",
                            Title = "Thấm nước trần nhà vệ sinh",
                            UpdatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 2,
                            Category = "security",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tôi làm rơi thẻ từ, cần cấp lại thẻ mới.",
                            Location = "Lễ tân",
                            Priority = "medium",
                            ReportedByAuthUserId = 103,
                            Status = "open",
                            Title = "Mất thẻ từ thang máy",
                            UpdatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.IncidentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<int>("AuthorAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_comments", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorAuthUserId = 201,
                            Content = "Đã tiếp nhận và cho kỹ thuật viên qua kiểm tra.",
                            CreatedAt = new DateTime(2024, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorAuthUserId = 202,
                            Content = "Đang liên hệ căn hộ tầng trên để khóa van nước tạm thời.",
                            CreatedAt = new DateTime(2024, 1, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorAuthUserId = 104,
                            Content = "Mong BQL xử lý nhanh giúp, nước chảy nhiều quá.",
                            CreatedAt = new DateTime(2024, 1, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            IncidentId = 2
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SendStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("notifications", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audience = "building_a",
                            Channel = "push",
                            Content = "Bảo trì thang số 1 từ 22h-24h ngày 15/05.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            FailedCount = 0,
                            IsRead = false,
                            SendStatus = "PENDING",
                            SentAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SentCount = 50,
                            Status = "sent",
                            TemplateId = 2,
                            Title = "Bảo trì thang máy Tòa A",
                            TotalRecipients = 50,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Audience = "all",
                            Channel = "push",
                            Content = "Vui lòng thanh toán phí quản lý tháng 5.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            FailedCount = 0,
                            IsRead = false,
                            ScheduledAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            SendStatus = "PENDING",
                            SentCount = 0,
                            Status = "scheduled",
                            TemplateId = 1,
                            Title = "Nhắc nợ phí tháng 5",
                            TotalRecipients = 200,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("notification_logs", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Channel = "push",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NotificationId = 1,
                            Recipient = "device_token_abc123",
                            ResidentId = 1,
                            SentAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "delivered"
                        },
                        new
                        {
                            Id = 2,
                            Channel = "push",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NotificationId = 1,
                            Recipient = "device_token_xyz789",
                            ResidentId = 2,
                            SentAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "delivered"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variables")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("notification_templates", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Kính gửi {resident_name}, vui lòng thanh toán phí dịch vụ tháng {month} trước ngày {due_date}.",
                            Channel = "push",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            IsActive = true,
                            Name = "Nhắc đóng phí tháng",
                            Subject = "Nhắc nhở thanh toán phí {month}",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variables = "[\"resident_name\",\"month\",\"due_date\"]"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Kính gửi quý cư dân, BQL xin thông báo bảo trì thang máy tòa {building} vào lúc {time}.",
                            Channel = "push",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByAuthUserId = 1,
                            IsActive = true,
                            Name = "Bảo trì thang máy",
                            Subject = "Thông báo bảo trì thang máy {building}",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Variables = "[\"building\",\"time\"]"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCategories")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("providers", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.ProviderServiceListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceList")
                        .HasColumnType("text");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("provider_service_listings", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .HasColumnType("text");

                    b.Property<bool>("IsBusinessOwner")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MoveInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("IdCard")
                        .IsUnique()
                        .HasFilter("\"IdCard\" IS NOT NULL");

                    b.ToTable("residents", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            AuthUserId = 101,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tuan.nv@gmail.com",
                            FullName = "Nguyễn Văn Tuấn",
                            Gender = "male",
                            IdCard = "001090123456",
                            IsBusinessOwner = false,
                            IsOwner = true,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0901111222",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 1,
                            AuthUserId = 102,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mai.tt@gmail.com",
                            FullName = "Trần Thị Mai",
                            Gender = "female",
                            IdCard = "001092654321",
                            IsBusinessOwner = false,
                            IsOwner = false,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0902222333",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 2,
                            AuthUserId = 103,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bach.lh@gmail.com",
                            FullName = "Lê Hoàng Bách",
                            Gender = "male",
                            IdCard = "001085112233",
                            IsBusinessOwner = false,
                            IsOwner = true,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0903333444",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 5,
                            AuthUserId = 104,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1980, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hung.pq@gmail.com",
                            FullName = "Phạm Quang Hưng",
                            Gender = "male",
                            IdCard = "001080998877",
                            IsBusinessOwner = false,
                            IsOwner = true,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0904444555",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 6,
                            AuthUserId = 105,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "thao.dt@gmail.com",
                            FullName = "Đặng Thu Thảo",
                            Gender = "female",
                            IdCard = "001095334455",
                            IsBusinessOwner = false,
                            IsOwner = true,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0905555666",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 7,
                            AuthUserId = 106,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1978, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phong.vd@gmail.com",
                            FullName = "Vũ Đình Phong",
                            Gender = "male",
                            IdCard = "001078556677",
                            IsBusinessOwner = false,
                            IsOwner = true,
                            MoveInDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "0906666777",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MgtApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MgtApprovedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("MgtRejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderRejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("RequestedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresMgtApproval")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ProviderId");

                    b.ToTable("service_requests", "townhub");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("UpdatedByAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_configs", "townhub");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "string",
                            Description = "Tên dự án hiển thị",
                            IsPublic = true,
                            Key = "project_name",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "TownHub"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "string",
                            Description = "Mã dự án (bất biến)",
                            IsPublic = false,
                            Key = "project_code",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "LUX_RES_01"
                        },
                        new
                        {
                            Id = 3,
                            DataType = "string",
                            Description = "Email hỗ trợ BQL",
                            IsPublic = true,
                            Key = "support_email",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "support@TownHub.vn"
                        },
                        new
                        {
                            Id = 4,
                            DataType = "string",
                            Description = "Hotline liên hệ",
                            IsPublic = true,
                            Key = "hotline",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1900 1234"
                        },
                        new
                        {
                            Id = 5,
                            DataType = "boolean",
                            Description = "Bật/tắt chế độ bảo trì",
                            IsPublic = false,
                            Key = "maintenance_mode",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.AccessEvent", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Resident", "Resident")
                        .WithMany("AccessEvents")
                        .HasForeignKey("ResidentId");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FaceProfile", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Resident", "Resident")
                        .WithOne("FaceProfile")
                        .HasForeignKey("TH.TownHub.Domain.Entities.FaceProfile", "ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Fee", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Fees")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.TownHub.Domain.Entities.FeeType", "FeeType")
                        .WithMany("Fees")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Incidents")
                        .HasForeignKey("ApartmentId");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.IncidentComment", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.NotificationTemplate", "Template")
                        .WithMany("Notifications")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Notification", "Notification")
                        .WithMany("Logs")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.TownHub.Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId");

                    b.Navigation("Notification");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Provider", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.ProviderServiceListing", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Provider", "Provider")
                        .WithMany("ServiceListings")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Resident", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("TH.TownHub.Domain.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("TH.TownHub.Domain.Entities.Provider", "Provider")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ProviderId");

                    b.Navigation("Apartment");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Incidents");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.FeeType", b =>
                {
                    b.Navigation("Fees");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Provider", b =>
                {
                    b.Navigation("ServiceListings");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("TH.TownHub.Domain.Entities.Resident", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("FaceProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
