"use client";

import { BarChart3, CalendarDays, CheckCircle2, CirclePlus, ClipboardList, Users, Vote } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";

type Choice = { label: string; votes: number };
type Poll = { id: number; title: string; description: string; audience: string; closesAt: string; voters: number; eligible: number; choices: Choice[]; voted?: number };

const initialPolls: Poll[] = [
  { id: 1, title: "Lựa chọn đơn vị quản lý vận hành năm 2026", description: "Xin ý kiến chủ hộ về đơn vị đồng hành cùng khu đô thị trong giai đoạn tiếp theo.", audience: "Chủ hộ", closesAt: "30/06/2026", voters: 148, eligible: 220, choices: [{ label: "Tiếp tục đơn vị hiện tại", votes: 82 }, { label: "Mời thầu đơn vị mới", votes: 66 }] },
  { id: 2, title: "Khảo sát khung giờ thu gom rác buổi tối", description: "Chọn khung giờ phù hợp nhất để hạn chế ảnh hưởng sinh hoạt của cư dân.", audience: "Cư dân tòa A", closesAt: "25/06/2026", voters: 91, eligible: 134, choices: [{ label: "18:00 – 19:00", votes: 33 }, { label: "19:00 – 20:00", votes: 45 }, { label: "20:00 – 21:00", votes: 13 }] },
];
const POLLS_STORAGE_KEY = "townhub.community.polls";

export default function PollCenter() {
  const { roles, hasPermission } = useAuth();
  const isAdmin = roles.some((role) => /admin|quản trị|quan tri/i.test(role.roleName)) || hasPermission("notification.manage") || hasPermission("notification.send");
  const [polls, setPolls] = useState<Poll[]>(() => {
    if (typeof window === "undefined") return initialPolls;
    try {
      const saved = localStorage.getItem(POLLS_STORAGE_KEY);
      return saved ? JSON.parse(saved) as Poll[] : initialPolls;
    } catch { return initialPolls; }
  });
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", audience: "Tất cả cư dân", closesAt: "", options: "Đồng ý\nKhông đồng ý" });
  const totalVotes = useMemo(() => polls.reduce((sum, poll) => sum + poll.voters, 0), [polls]);
  useEffect(() => { localStorage.setItem(POLLS_STORAGE_KEY, JSON.stringify(polls)); }, [polls]);
  function vote(pollId: number, choiceIndex: number) { setPolls((items) => items.map((poll) => poll.id !== pollId || poll.voted !== undefined ? poll : { ...poll, voters: poll.voters + 1, voted: choiceIndex, choices: poll.choices.map((choice, i) => i === choiceIndex ? { ...choice, votes: choice.votes + 1 } : choice) })); toast.success("Đã ghi nhận phiếu bầu của bạn"); }
  function createPoll() { const choices = form.options.split("\n").map((x) => x.trim()).filter(Boolean); if (!form.title.trim() || choices.length < 2) return toast.error("Nhập tiêu đề và ít nhất 2 lựa chọn"); setPolls((items) => [{ id: Date.now(), title: form.title, description: form.description, audience: form.audience, closesAt: form.closesAt || "Chưa đặt", voters: 0, eligible: 220, choices: choices.map((label) => ({ label, votes: 0 })) }, ...items]); setForm({ title: "", description: "", audience: "Tất cả cư dân", closesAt: "", options: "Đồng ý\nKhông đồng ý" }); setShowCreate(false); toast.success("Đã tạo khảo sát và sẵn sàng gửi đến cư dân"); }
  function editPoll(poll: Poll) { const title = prompt("Tiêu đề khảo sát", poll.title); if (!title?.trim()) return; const description = prompt("Mô tả khảo sát", poll.description); setPolls((items) => items.map((item) => item.id === poll.id ? { ...item, title, description: description ?? item.description } : item)); toast.success("Đã cập nhật khảo sát"); }
  function deletePoll(id: number) { if (!confirm("Bạn có chắc muốn xóa khảo sát này?")) return; setPolls((items) => items.filter((item) => item.id !== id)); toast.success("Đã xóa khảo sát"); }
  return <div className="mx-auto max-w-7xl space-y-6 pb-10">
    <div className="flex flex-col justify-between gap-4 rounded-2xl border border-white/5 bg-[#111] p-6 md:flex-row md:items-center"><div className="flex items-center gap-4"><div className="flex size-12 items-center justify-center rounded-xl border border-violet-500/30 bg-violet-500/15"><Vote className="size-6 text-violet-300" /></div><div><h1 className="text-2xl font-bold text-white">Ý kiến & <span className="text-violet-300">Khảo sát cư dân</span></h1><p className="mt-1 text-sm text-zinc-400">Quản trị khảo sát và thống kê phản hồi cư dân.</p></div></div>{isAdmin && <button onClick={() => setShowCreate(true)} className="flex items-center justify-center gap-2 rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-violet-400"><CirclePlus className="size-4" />Tạo khảo sát</button>}</div>
    <div className="grid gap-4 md:grid-cols-3">{[{ icon: ClipboardList, label: "Khảo sát đang mở", value: polls.length }, { icon: Users, label: "Tổng lượt tham gia", value: totalVotes }, { icon: BarChart3, label: "Tỷ lệ tham gia", value: `${Math.round(totalVotes / polls.reduce((s, p) => s + p.eligible, 0) * 100)}%` }].map((stat) => <div key={stat.label} className="flex items-center gap-4 rounded-2xl border border-white/5 bg-[#111] p-5"><div className="rounded-xl bg-violet-500/10 p-3"><stat.icon className="size-5 text-violet-300" /></div><div><p className="text-xs text-zinc-400">{stat.label}</p><p className="text-2xl font-bold text-white">{stat.value}</p></div></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-2">{polls.map((poll) => { const tally = poll.choices.reduce((sum, choice) => sum + choice.votes, 0); return <article key={poll.id} className="rounded-2xl border border-white/5 bg-[#111] p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><span className="rounded-full bg-violet-500/10 px-2.5 py-1 text-xs font-semibold text-violet-300">{poll.audience}</span><h2 className="mt-3 text-lg font-bold text-white">{poll.title}</h2><p className="mt-1 text-sm text-zinc-400">{poll.description}</p></div>{poll.voted !== undefined && <CheckCircle2 className="size-5 shrink-0 text-emerald-400" />}</div><div className="space-y-3">{poll.choices.map((choice, index) => { const pct = tally ? Math.round(choice.votes / tally * 100) : 0; return <button key={choice.label} onClick={() => vote(poll.id, index)} disabled={poll.voted !== undefined} className={`w-full overflow-hidden rounded-xl border p-3 text-left transition-colors ${poll.voted === index ? "border-violet-400/50 bg-violet-500/10" : "border-white/10 bg-white/[0.02] hover:border-violet-400/40"}`}><div className="flex justify-between text-sm"><span className="font-medium text-zinc-100">{choice.label}</span><span className="text-zinc-400">{choice.votes} phiếu · {pct}%</span></div><div className="mt-2 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-violet-400" style={{ width: `${pct}%` }} /></div></button>})}</div><div className="mt-5 flex justify-between border-t border-white/5 pt-4 text-xs text-zinc-500"><span>{poll.voters}/{poll.eligible} cư dân đã tham gia</span><span className="flex items-center gap-1"><CalendarDays className="size-3" />Đóng: {poll.closesAt}</span></div></article>; })}</div>
    {isAdmin && <section className="rounded-2xl border border-white/5 bg-[#111] p-6"><h2 className="font-bold text-white">CRUD khảo sát</h2><div className="mt-4 divide-y divide-white/10">{polls.map((poll) => <div key={poll.id} className="flex items-center justify-between gap-3 py-3"><span className="text-sm text-zinc-200">{poll.title}</span><div className="flex gap-2"><button onClick={() => editPoll(poll)} className="rounded-lg border border-violet-400/30 px-3 py-1.5 text-xs text-violet-300">Sửa</button><button onClick={() => deletePoll(poll.id)} className="rounded-lg border border-rose-400/30 px-3 py-1.5 text-xs text-rose-300">Xóa</button></div></div>)}</div></section>}
    {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#181818] p-6"><h2 className="text-lg font-bold text-white">Tạo khảo sát mới</h2><div className="mt-5 space-y-4"><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Câu hỏi khảo sát *" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white" /><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Mô tả ngắn" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white" /><div className="grid grid-cols-2 gap-3"><select value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })} className="rounded-xl border border-white/10 bg-black px-3 py-3 text-sm text-white [color-scheme:dark]"><option className="bg-black text-white">Tất cả cư dân</option><option className="bg-black text-white">Chủ hộ</option><option className="bg-black text-white">Cư dân theo tầng</option></select><input type="date" value={form.closesAt} onChange={(e) => setForm({ ...form, closesAt: e.target.value })} className="rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white" /></div><textarea value={form.options} onChange={(e) => setForm({ ...form, options: e.target.value })} rows={4} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white" /></div><div className="mt-6 flex justify-end gap-3"><button onClick={() => setShowCreate(false)} className="px-4 py-2 text-sm text-zinc-400">Hủy</button><button onClick={createPoll} className="rounded-xl bg-violet-500 px-4 py-2 text-sm font-bold text-white">Tạo & công bố</button></div></div></div>}
  </div>;
}
