// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TH.Auth.Infrastructure;

#nullable disable

namespace TH.WebAPI.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260225034856_AuthV1")]
    partial class AuthV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.Property<int>("auditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("auditID"));

                    b.Property<string>("action")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("detail")
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .HasColumnType("text");

                    b.Property<string>("result")
                        .HasColumnType("text");

                    b.Property<string>("userAgent")
                        .HasColumnType("text");

                    b.Property<int?>("userID")
                        .HasColumnType("integer");

                    b.HasKey("auditID");

                    b.HasIndex("userID");

                    b.ToTable("AuthAuditLog", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.Property<int>("mfaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("mfaID"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("enabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("enrollmentStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("lastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("recoveryCodes")
                        .HasColumnType("text");

                    b.Property<string>("secret")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("mfaID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.HasIndex("userID", "type")
                        .IsUnique();

                    b.ToTable("AuthMfaSecret", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Property<int>("sessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sessionID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .HasColumnType("text");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userAgent")
                        .HasColumnType("text");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthUserSession", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Property<int>("permissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("permissionID"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permissionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("permissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.HasKey("permissionID");

                    b.ToTable("AuthPermission", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roleID"));

                    b.Property<bool>("isDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("roleDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.HasKey("roleID");

                    b.HasIndex("roleName")
                        .IsUnique();

                    b.ToTable("AuthRole", "auth");

                    b.HasData(
                        new
                        {
                            roleID = 1,
                            isDefault = false,
                            roleDescription = "Quản trị viên",
                            roleName = "admin",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 2,
                            isDefault = false,
                            roleDescription = "Quản lý nội dung",
                            roleName = "content_manager",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 3,
                            isDefault = false,
                            roleDescription = "Quản lý người dùng",
                            roleName = "user_manager",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 4,
                            isDefault = false,
                            roleDescription = "Quản lý tài chính",
                            roleName = "finance_manager",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 10,
                            isDefault = true,
                            roleDescription = "Khách hàng",
                            roleName = "customer",
                            scope = "user"
                        },
                        new
                        {
                            roleID = 11,
                            isDefault = false,
                            roleDescription = "Khách hàng VIP",
                            roleName = "customer-vip",
                            scope = "user"
                        });
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.Property<int>("rolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rolePermissionID"));

                    b.Property<int>("permissionID")
                        .HasColumnType("integer");

                    b.Property<int>("roleID")
                        .HasColumnType("integer");

                    b.HasKey("rolePermissionID");

                    b.HasIndex("permissionID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthRolePermission", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("roleID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("userID", "roleID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthUserRole", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.Property<int>("emailVerificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("emailVerificationID"));

                    b.Property<string>("codeHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("emailVerificationID");

                    b.HasIndex("userID");

                    b.ToTable("AuthEmailVerification", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.Property<int>("passwordResetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("passwordResetID"));

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("passwordResetID");

                    b.HasIndex("userID");

                    b.ToTable("AuthPasswordReset", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.Property<int>("refreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("refreshTokenID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("sessionID")
                        .HasColumnType("integer");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("refreshTokenID");

                    b.HasIndex("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthRefreshToken", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthProfile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("profileID"));

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("profileID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("AuthProfile", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthUser", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("googleSub")
                        .HasColumnType("text");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("tokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("userID");

                    b.ToTable("AuthUser", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("auditLogs")
                        .HasForeignKey("userID");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithOne("mfaSecret")
                        .HasForeignKey("TH.Auth.Domain.MFA.AuthMfaSecret", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("sessions")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.HasOne("TH.Auth.Domain.Role.AuthPermission", "permission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("permissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("rolePermissions")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.HasOne("TH.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("emailVerifications")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("passwordResets")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.HasOne("TH.Auth.Domain.MFA.AuthUserSession", "session")
                        .WithMany("refreshTokens")
                        .HasForeignKey("sessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("refreshTokens")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthProfile", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithOne("profile")
                        .HasForeignKey("TH.Auth.Domain.User.AuthProfile", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Navigation("refreshTokens");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Navigation("rolePermissions");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthUser", b =>
                {
                    b.Navigation("auditLogs");

                    b.Navigation("emailVerifications");

                    b.Navigation("mfaSecret");

                    b.Navigation("passwordResets");

                    b.Navigation("profile");

                    b.Navigation("refreshTokens");

                    b.Navigation("sessions");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
